language: node_js
node_js:
- lts/*
script:
- grunt deploy
- npm run test:unit
deploy:
  provider: gae
  keyfile: client-secret.json
  project: gtm-templates-com
  default: true
  skip_cleanup: true
before_script:
- npm install grunt-cli -g
before_install:
- openssl aes-256-cbc -K $encrypted_6fc55035f215_key -iv $encrypted_6fc55035f215_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
