language: node_js
script:
  - npm run lint
  - npm test
deploy:
  provider: gae
  keyfile: "client-secret.json"
  project: "gtm-templates-com"
before_install:
- openssl aes-256-cbc -K $encrypted_c43d0a9d19c9_key -iv $encrypted_c43d0a9d19c9_iv
  -in client-secret.json.enc -out client-secret.json -d
